"""
Códigos IFIS interbancarios — Banco Pichincha Ecuador.
Fuente: Documento "Códigos de IFIS" oficial de Banco Pichincha.

Provee buscar_codigo_banco(nombre) para resolver el nombre de banco
tal como aparece en el sistema contable al código de 4 dígitos.
"""

import unicodedata
import re

# ── Tabla completa código → nombre oficial ────────────────────────────────────
CODIGOS_IFIS: dict[str, str] = {
    "0010": "BANCO PICHINCHA",
    "0017": "BANCO DE GUAYAQUIL S.A",
    "0024": "BANCO CITIBANK",
    "0025": "BANCO MACHALA",
    "0029": "BANCO DE LOJA",
    "0030": "BANCO DEL PACIFICO",
    "0032": "BANCO INTERNACIONAL",
    "0034": "BANCO AMAZONAS",
    "0035": "BANCO DEL AUSTRO",
    "0036": "BANCO PRODUBANCO",
    "0037": "BANCO BOLIVARIANO",
    "0039": "COMERCIAL DE MANABI",
    "0042": "BANCO GENERAL RUMINAHUI S.A.",
    "0043": "BANCO DEL LITORAL S.A.",
    "0059": "BANCO SOLIDARIO",
    "0060": "BANCO PROCREDIT S.A.",
    "0061": "BANCO CAPITAL",
    "0065": "BANCO DESARROLLO DE LOS PUEBLOS S.A.",
    "0066": "BANECUADOR B.P.",
    "0070": "COOP. AHORRO Y CREDITO 15 DE ABRIL LTDA",
    "0076": "COOP. JARDIN AZUAYO",
    "0079": "COOP.DE AHORRO Y CREDITO POLICIA NACIONAL",
    "0082": "FINANCOOP",
    "0201": "BANCO DELBANK S.A.",
    "0203": "CACPECO LTDA",
    "0204": "C.PEQ.EMPRESA DE PASTAZA",
    "0205": "COOP. AHORRO Y CREDITO 23 DE JULIO",
    "0206": "COOP. AHORRO Y CREDITO 29 DE OCTUBRE",
    "0207": "COOP. AHORRO Y CREDITO ANDALUCIA",
    "0208": "COOP. AHORRO Y CREDITO COTOCOLLAO",
    "0210": "COOP. AHORRO Y CREDITO EL SAGRARIO",
    "0211": "COOP. AHORRO Y CREDITO GUARANDA LTDA",
    "0213": "COOP. JUVENTUD ECUATORIANA PROGRESISTA LTDA.(JEP)",
    "0216": "COOP. AHORRO Y CREDITO OSCUS",
    "0217": "COOP. AHORRO Y CREDITO PABLO MUNOZ VEGA",
    "0218": "COOP A Y C COOPROGRESO LTDA",
    "0219": "COOP. AHORRO Y CREDITO RIOBAMBA",
    "0220": "COOP. AHORRO Y CREDITO SAN FRANCISCO",
    "0222": "COOP. AHORRO Y CREDITO TULCAN",
    "0223": "COOP. DE AHORRO Y CREDITO ATUNTAQUI LTDA.",
    "0224": "COOP. DE AHORRO Y CREDITO COMERCIO LTDA PORTOVIEJO",
    "0225": "COOP. DE AHORRO Y CREDITO LA DOLOROSA LTDA",
    "0226": "COOP. PREVISION AHORRO Y DESARROLLO",
    "0227": "COOP.AHORRO Y CREDITO ALIANZA DEL VALLE LTDA",
    "0229": "COOP.AHORRO Y CREDITO CHONE LTDA",
    "0231": "COOPERATIVA DE AHORRO Y CREDITO SANTA ANA LTDA",
    "0232": "BANCO DINERS CLUB",
    "0233": "MUTUALISTA AMBATO",
    "0234": "MUTUALISTA AZUAY",
    "0236": "MUTUALISTA IMBABURA",
    "0238": "MUTUALISTA PICHINCHA",
    "0240": "COOP DE A. Y C. CORPORACION CENTRO LTDA.",
    "0242": "COOP. DE A. Y C. CORDILLERA DE LOS ANDES LTDA.",
    "0243": "COOP. DE A. Y C. PUERTO FRANCISCO DE ORELLANA",
    "0244": "COOP. DE A Y C. LUZ DEL VALLE",
    "0245": "COOP. DE A Y C. ESPERANZA Y PROGRESO DEL VALLE",
    "0247": "COOP. DE A. Y C. COOPARTAMOS LTDA",
    "0248": "COOP DE A. Y C. SAN JUAN DE COTOGCHOA",
    "0249": "COOP. DE A. Y C. EMPRENDEDORES COOPEMPRENDER LTDA.",
    "0250": "COOP. DE A. Y C. NUEVA LOJA LTDA.",
    "0251": "COOPERATIVA DE AHORRO Y CREDITO PICHINCHA LTDA.",
    "0252": "COOP. CREDITO Y AHORRO SAN FRANCISCO DE ASIS",
    "0253": "COOPERATIVA DE AHORRO Y CREDITO FINANZAS CORPORATIVAS",
    "0255": "COOPERATIVA DE AHORRO Y CREDITO SAN BARTOLO LTDA",
    "0257": "COOP. DE A. Y C. DEL EMIGRANTE ECUATORIANO Y SU FA",
    "0258": "COOP. AHORRO Y CREDITO LA LIBERTAD LTDA",
    "0259": "COAC CUNA DE LA NACIONALIDAD LTDA.",
    "0262": "COOPERATIVA DE AHORRO Y CREDITO SANTA ISABEL LTDA.",
    "0263": "COOPERATIVA DE AHORRO Y CREDITO GANANSOL LTDA",
    "0264": "COOPERATIVA DE AHORRO Y CREDITO DEL AZUAY",
    "0268": "COOPERATIVA DE AHORRO Y CREDITO MULTIEMPRESARIAL L",
    "0270": "COOP. AHORRO Y CREDITO JUAN DE SALINAS LTDA.",
    "0271": "COOP. AHORRO Y CREDITO PUELLARO LTDA",
    "0272": "COOP. AHORRO Y CREDITO NUEVA JERUSALEN",
    "0275": "COOP. DE AHORRO Y CREDITO CHOLA CUENCANA LTDA.",
    "0276": "COOP. AHORRO Y CREDITO TENA LTDA.",
    "0277": "COOP. AHORRO Y CREDITO DE LA PEQUENA EMPRESA GUALAQUIZA",
    "0278": "COOP. AHORRO Y CREDITO ALIANZA MINAS LTDA.",
    "0279": "COOP. DE AHORRO Y CREDITO PEDRO MONCAYO LTDA.",
    "0281": "COOPERATIVA DE AHORRO Y CREDITO PROVIDA",
    "0283": "COOPERATIVA DE AHORRO Y CREDITO SAN JOSE S.J.",
    "0285": "COOP. AHORRO Y CREDITO SENOR DE GIRON",
    "0287": "COOP. DE AHORRO Y CREDITO EDUC.DEL TUNGURAHUA LTDA",
    "0288": "COOP. AHORRO Y CREDITO LOS RIOS",
    "0290": "COOPERATIVA 15 DE AGOSTO PILACOTO",
    "0291": "COOP. DE AHORRO Y CREDITO CRISTO REY",
    "0292": "COOP. DE AHORRO Y CREDITO EDUCADORES DE CHIMBORAZO",
    "0293": "COOPERATIVA DE AHORRO Y CREDITO MINGA LTDA.",
    "0294": "COOP. DE AHORRO Y CREDITO 4 DE OCTUBRE LTDA.",
    "0295": "COOP. DE AHORRO Y CREDITO CREDI FACIL LTDA.",
    "0296": "COOP. DE AHORRO Y CREDITO ALFONSO JARAMILLO C.C.C.",
    "0299": "COAC CREDIMAS",
    "0301": "COOP. DE A. Y C. LA FLORESTA LTDA.",
    "0303": "COOP. DE A. Y C. MULTICULTURAL BANCO INDIGENA LTDA",
    "0304": "COOP DE A. Y C. CRECER WINARI LTDA.",
    "0305": "COOP. DE A. Y C. BANOS DE AGUA SANTA LTDA.",
    "0306": "COOP. DE AHORRO Y CREDITO 1 DE JULIO",
    "0309": "COOPERATIVA DE AHORRO Y CREDITO SAN ANTONIO LTDA.",
    "0310": "COOP. DE AHORRO Y CREDITO FUNDAR",
    "0312": "COOP. AHORRO Y CREDITO METROPOLIS LTDA.",
    "0313": "COOP. DE AHORRO Y CREDITO EL CAFETAL",
    "0314": "COOP.DE AHORRO Y CREDITO MICROEMPRESARIAL SUCRE",
    "0316": "COOPERATIVA DE AHORRO Y CREDITO JOYOCOTO LTDA.",
    "0317": "COOP. A Y C SAN ANTONIO LTDA. IMBABURA",
    "0318": "COOP. DE A. Y C. UNIOTAVALO LTDA.",
    "0319": "COOP. DE A. Y C. UNION EL EJIDO",
    "0323": "BANCO AMIBANK S.A",
    "0324": "COOP. CALCETA LTDA",
    "0325": "COOP. AHORRO Y CREDITO 9 DE OCTUBRE LTDA",
    "0328": "COOP. AHORRO Y CREDITO SAN GABRIEL LTDA.",
    "0329": "COOP. AHORRO Y CREDITO SAN JOSE LTDA",
    "0330": "COOP. AHORRO Y CREDITO SAN MIGUEL DE LOS BANCOS",
    "0332": "COOP. AHORRO Y CREDITO SEMILLA DEL PROGRESO LTDA",
    "0333": "COOP. AHORRO. Y CREDI. MUJERES UNIDAS TANTANAKUSHK",
    "0334": "COOP. DE AHORRO Y CRED. SANTA ROSA LTDA",
    "0335": "COOP. DE AHORRO Y CREDITO ONCE DE JUNIO",
    "0336": "COOP. DE A. Y C. PUJILI LTDA",
    "0337": "COOP. DE A. Y C. CREDIL LTDA.",
    "0339": "COOP. DE A. Y C. MUSHUK PAKARI LTDA.",
    "0340": "COOP. DE A. Y C. UNIBLOCK Y SERVICIOS LTDA.",
    "0342": "COOP. DE A. Y C. FUTURO LAMANENSE",
    "0343": "COOP. DE A. Y C. SAQUISILI LTDA.",
    "0344": "COOP. DE A. Y C. INNOVACION ANDINA LTDA.",
    "0345": "COOP.DE A.Y C. EL COMERCIANTE LTDA (MIES)",
    "0346": "COOP. DE A. Y C. MUSHUK WASI LTDA (MIES)",
    "0347": "COOPERATIVA DE AHORRO Y CREDITO SOLIDARIA LTDA",
    "0348": "COOPERATIVA DE AHORRO Y CREDITO LLANGANATES",
    "0350": "COOP.AHO Y CREDITO DE LA PEQ. EMP. DE LOJA CACPE",
    "0351": "COOPERATIVA DE AHORRO Y CREDITO ECONOMIA DEL SUR C",
    "0355": "COOP.DE AHORRO Y CREDITO 29 DE ENERO",
    "0356": "COOP. AHORRO Y CREDITO AGRARIA MUSHUK KAWSAY LTDA.",
    "0357": "COOPERATIVA DE AHORRO Y CREDITO RUNA SHUNGO LTDA.",
    "0358": "COOP. DE A. Y C. SAN MARCOS",
    "0359": "COOP. DE A. Y C. ANTORCHA LTDA.",
    "0361": "COOP. DE A. Y C. INDIGENAS GALAPAGOS LTDA.",
    "0362": "COOP. AHORRO Y CREDITO CAMARA DE COMERCIO DEL CANT",
    "0363": "COOPERATIVA DE AHORRO Y CREDITO LA BENEFICA LTDA.",
    "0364": "COOP.DE AHORRO Y CREDITO ABDON CALDERON LTDA.",
    "0365": "COOP. A Y C CAMARA DE COMERCIO CANTON EL CARMEN L",
    "0366": "COOP.DE AHORRO Y CREDITO AGROPRODUCTIVA MANABI LTD",
    "0367": "COOP. DE AHORRO Y CRED. LA INMACULADA DE SAN PLACI",
    "0368": "COOP. AHORRO Y CREDITO CACPE MANABI",
    "0369": "COOP.AHORRO Y CREDITO MAGISTERIO MANABITA LIMITADA",
    "0370": "COAC TIENDA DE DINERO LTDA.",
    "0371": "COOP.A.Y C. SANTA MARIA DE LA MANGA DEL CURA LTDA.",
    "0375": "COOP. AHORRO Y CREDITO CAMARA DE COMERCIO INDIGENA",
    "0379": "COOP. DE A. Y C. GUAMOTE LTDA.",
    "0381": "COOP. DE A. Y C. SOL DE LOS ANDES LTDA.",
    "0382": "COOP. DE A.Y C. PRODUC. AHORRO INVERS. SERVICIO P.",
    "0383": "COOP. DE A. Y C. FRANDESC LTDA.",
    "0384": "COOP. DE A. Y C. NUKA LLAKTA LTDA.",
    "0385": "COOP. DE A Y C. CAMARA DE COMERCIO RIOBAMBA",
    "0386": "COOP. DE A. Y C. BASHALAN LTDA.",
    "0400": "COOP. WARMIKUNAPAK RIKCHARI",
    "0403": "COOP AHORRO Y CREDITO MI TIERRA",
    "0404": "COOP AHORRO Y CREDITO DE LA PEQ EMP CACPE YANZATZA",
    "0405": "COOP AHORRO Y CREDITO FUNDESARROLLO",
    "0408": "COOP DE AHORRO Y CREDITO NUEVA HUANCAVILCA",
    "0410": "COOP DE AHORRO Y CREDITO ERCO LTDA",
    "0412": "COOP AHORRO Y CREDITO MUSHUC RUNA LTDA",
    "0414": "COOP DE AHORRO Y CREDITO AMBATO LTDA",
    "0415": "COOP DE AHORRO Y CREDITO DORADO LTDA",
    "0416": "COOP DE AHORRO Y CREDITO NUESTROS ABUELOS LTDA",
    "0417": "COOP DE AHORRO Y CREDITO ARTESANOS LTDA",
    "0418": "COOP DE AHORRO Y CREDITO SANTA ANITA LTDA",
    "0419": "COOP DE AHORRO Y CREDITO HUAYCO PUNGO LTDA",
    "0420": "COOP MANUEL ESTEBAN GODOY ORTEGA LTDA COOPMEGO",
    "0421": "COOP AHORRO Y CREDITO PADRE JULIAN LORENTE LTDA",
    "0423": "COOP DE AHORRO Y CREDITO MARCABELI LTDA",
    "0424": "COOP DE AHORRO Y CREDITO AGRICOLA JUNIN LTDA",
    "0425": "COOP DE AHORRO Y CREDITO PUERTO LOPEZ LTDA",
    "0427": "COOP DE AHORRO Y CREDITO NUEVA ESPERANZA",
    "0428": "COOP DE AHORRO Y CREDITO SAN JORGE LTDA",
    "0429": "COOP DE AHORRO Y CREDITO FERNANDO DAQUILEMA",
    "0435": "COOP DE A Y C EDUCADORES DE PASTAZA LTDA",
    "0450": "COOP. A. Y C. DE LA PEQ. EMP. CACPE ZAMORA LTDA",
    "0452": "COOP. DE AHORRO Y CREDITO EL CALVARIO LTDA",
    "0453": "COOP. DE A. Y C. JUAN PIO DE MORA LTDA",
    "0455": "COOP. DE AHORRO Y CREDITO PUCARA LTDA",
    "0456": "COOP. A. Y C. CAMARA DE COMERCIO DE PINDAL CADECOP",
    "0461": "BANCO DEL INSTITU ECUATORIANO DE SEGURIDAD SOCIAL",
    "0462": "COOP DE A Y C DE SERV PUBL DEL MIN EDUCACION Y CUL",
    "0464": "COOP DE A Y C COCA LTDA",
    "0465": "COOP DE AHORRO Y CREDITO PILAHUIN TIO LTDA",
    "0467": "COOP DE AHORRO Y CREDITO HUAICANA LTDA",
    "0468": "COOP DE A Y C CREDISUR LTDA",
    "0471": "COOP DE AHORRO Y CREDITO HUAQUILLAS LTDA",
    "0473": "COOP DE AHORRO Y CREDITO CAC-CICA MIES",
    "0475": "COOP DE A Y C VENCEDORES DE TUNGURAHUA",
    "0476": "COOP A Y C ECUAFUTURO LTDA",
    "0477": "COOP DE A Y C MAQUITA CUSHUN LTDA",
    "0478": "COOP DE A Y C VALLES DEL LIRIO",
    "0479": "COOP ESFUERZO UNIDO PARA EL DESARR DEL CHILCO",
    "0480": "COOP A Y C CARROCEROS DE TUNGURAHUA",
    "0481": "COOP DE AHORRO Y CREDITO SIMIATUG LTDA",
    "0482": "COOP DE A Y C SINCHI RUNA LTDA",
    "0483": "COOP DE A Y C SANTA ROSA DE PAUTAN LTDA",
    "0484": "COOP DE AHORRO Y CREDITO SAN MIGUEL DE SIGCHOS",
    "0485": "COOP DE A Y C SIERRA CENTRO LTDA",
    "0486": "COOP DE A Y C GONZANAMA MIES",
    "0487": "COOP DE AHORRO Y CREDITO QUILANGA LTDA",
    "0489": "COOP DE A Y C CREDIAMIGO LTDA LOJA MIES",
    "0490": "COOP DE AHORRO Y CREDITO FORTUNA MIES",
    "0492": "COOP DE AHORRO Y CREDITO CACPE CELICA",
    "0493": "COOP DE A Y C FUTURO Y PROGRESO DE GALAPAGOS LTDA",
    "0494": "COOP DE A Y C SUMAC LLACTA LTDA",
    "0495": "COOP DE A Y C LUCHA CAMPESINA LTDA",
    "0497": "COOP DE A Y C MAQUITA CUSHUNCHIC LTDA",
    "0498": "COOP A Y C FOCLA",
    "0499": "COOP DE A Y C CASAG LTDA",
    "0500": "BANCO D MIRO SA",
    "0502": "COOP DE A Y C FINANCIERA INDIGENA LTDA",
    "0503": "COOP A Y C 20 FEBRERO LTDA",
    "0504": "COOP DE A Y C DEL COL. FISC. VICENTE ROCAFUERTE",
    "0505": "COOP DE A Y C JADAN LTDA (MIES)",
    "0510": "COOP DE A Y C ACCION TUNGURAHUA LTDA",
    "0511": "COOP DE A Y C PIJAL",
    "0514": "COOP DE A Y C CATAMAYO LTDA",
    "0517": "BANCO COOPNACIONAL SA",
    "0518": "COOP DE A Y C 16 DE JUNIO",
    "0519": "COOP A Y C ESC SUP POLITEC AGROP DE MANABI MANUEL",
    "0521": "COOP DE A Y C EDUCACIONES TULCAN LTDA",
    "0524": "DE AHORRO Y CREDITO CRECIENDO JUNTOS",
    "0526": "COOP DE AHORRO Y CREDITO FASAYNAN LTDA",
    "0537": "CORPORACION EN LAS HUELLAS DEL BCO GRAMEEN",
    "0909": "BANCO VISIONFUND ECUADOR S.A.",
}

# ── Palabras a ignorar en el matching ────────────────────────────────────────
_STOPWORDS = {
    "BANCO", "BANCOS", "DE", "DEL", "LA", "LOS", "LAS", "EL", "Y", "SA",
    "SAS", "SA.", "S.A", "S.A.", "LTDA", "LTDA.", "BP", "B.P.",
    "COOP", "COOPERATIVA", "AHORRO", "CREDITO", "COAC",
    "MUTUALISTA", "FINANCIERA", "CIA", "CIA.", "C.A",
}


def _normalizar(texto: str) -> str:
    """Elimina acentos, pasa a mayúsculas y quita caracteres especiales."""
    texto = texto.upper().strip()
    # Quitar acentos
    texto = unicodedata.normalize("NFD", texto)
    texto = "".join(c for c in texto if unicodedata.category(c) != "Mn")
    # Quedarse solo con alfanuméricos y espacios
    texto = re.sub(r"[^A-Z0-9\s]", " ", texto)
    return re.sub(r"\s+", " ", texto).strip()


def _palabras_clave(texto_norm: str) -> set[str]:
    """Retorna palabras relevantes (sin stopwords y de ≥ 3 letras)."""
    return {
        w for w in texto_norm.split()
        if w not in _STOPWORDS and len(w) >= 3
    }


# Precalcular índice invertido: palabras_clave → código
_INDICE: dict[str, list[str]] = {}
for _cod, _nom in CODIGOS_IFIS.items():
    for _pal in _palabras_clave(_normalizar(_nom)):
        _INDICE.setdefault(_pal, []).append(_cod)


def buscar_codigo_banco(nombre_banco: str) -> str:
    """
    Devuelve el código IFIS de 4 dígitos (ej. '0010') dado el nombre
    del banco tal como aparece en el sistema contable.
    Retorna '' si no se puede determinar.
    """
    if not nombre_banco or str(nombre_banco).strip() in ("", "nan", "None"):
        return ""

    nom_norm = _normalizar(str(nombre_banco))

    # 1. Coincidencia exacta en nombre normalizado completo
    for cod, nom_ofic in CODIGOS_IFIS.items():
        if _normalizar(nom_ofic) == nom_norm:
            return cod

    # 2. El input está contenido en el nombre oficial (o viceversa)
    for cod, nom_ofic in CODIGOS_IFIS.items():
        ofic_norm = _normalizar(nom_ofic)
        if nom_norm in ofic_norm or ofic_norm in nom_norm:
            return cod

    # 3. Votos por palabras clave (mayor cantidad de palabras en común gana)
    palabras_input = _palabras_clave(nom_norm)
    if not palabras_input:
        return ""

    votos: dict[str, int] = {}
    for pal in palabras_input:
        for cod in _INDICE.get(pal, []):
            votos[cod] = votos.get(cod, 0) + 1

    if votos:
        mejor_cod = max(votos, key=lambda c: votos[c])
        return mejor_cod

    return ""


def nombre_banco(codigo: str) -> str:
    """Devuelve el nombre oficial dado el código, o el propio código si no existe."""
    return CODIGOS_IFIS.get(codigo, codigo)
